version: '3.8'

services:
  ipfs:
    image: ipfs/kubo:latest
    container_name: ipfs-node-prod
    environment:
      - IPFS_PROFILE=server
      # Optional: reduce resource usage
      - IPFS_FD_MAX=4096
    ports:
      - "4001:4001"              # P2P (Swarm) - public
      - "127.0.0.1:5001:5001"    # HTTP RPC API - localhost only (security)
      - "127.0.0.1:8080:8080"    # HTTP Gateway - localhost only (security)
    volumes:
      - ipfs_data:/data/ipfs
      - ipfs_staging:/export
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "ipfs id || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G

  ipfs-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: ipfs-api-prod
    ports:
      - "127.0.0.1:3000:3000"  # Localhost only
    environment:
      - IPFS_API_URL=http://ipfs:5001/api/v0
    depends_on:
      - ipfs
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M

volumes:
  ipfs_data:
    driver: local
  ipfs_staging:
    driver: local
