version: '3.8'

# OPTION 1: Public Access (Simple)
# Binds IPFS API and Gateway to 0.0.0.0 (all interfaces)
# WARNING: This exposes IPFS API to the internet - anyone can use your node
# Use for development/testing or when you'll add middleware protection later

services:
  ipfs:
    image: ipfs/kubo:latest
    container_name: ipfs-node-prod
    environment:
      - IPFS_PROFILE=server
      - IPFS_FD_MAX=4096
    ports:
      - "4001:4001"          # P2P (Swarm) - public
      - "0.0.0.0:5001:5001"  # HTTP RPC API - PUBLIC (all interfaces)
      - "0.0.0.0:8080:8080"  # HTTP Gateway - PUBLIC (all interfaces)
    volumes:
      - ipfs_data:/data/ipfs
      - ipfs_staging:/export
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "ipfs id || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G

volumes:
  ipfs_data:
    driver: local
  ipfs_staging:
    driver: local
